//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multiplier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multiplier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///&lt;TITLE&gt;Multiplier&lt;/TITLE&gt;
        ///&lt;/HEAD&gt;
        ///&lt;BODY BGCOLOR=&quot;FFFFFF&quot;&gt;
        ///	&lt;!-- TradingView Widget BEGIN --&gt;
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;https://s3.tradingview.com/tv.js&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///	new TradingView.widget({
        ///	  &quot;autosize&quot;: true,
        ///	  &quot;symbol&quot;: &quot;COINBASE:LTCUSD&quot;,
        ///	  &quot;interval&quot;: &quot;5&quot;,
        ///	  &quot;timezone&quot;: &quot;America/Los_Angeles&quot;,
        ///	  &quot;theme&quot;: &quot;Light&quot;,
        ///	  &quot;style&quot;: &quot;2&quot;,
        ///	  &quot;locale&quot;: &quot;en&quot;,
        ///	  &quot;toolbar_bg&quot;: &quot;#f1f3f6&quot;,
        ///	  &quot;enable_publishing&quot;: false,
        ///	  &quot;withdateranges&quot;: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TradeWidgetPage {
            get {
                return ResourceManager.GetString("TradeWidgetPage", resourceCulture);
            }
        }
    }
}
